project:
  type: website
  output-dir: docs

website:
  title: "My website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Assignments"
        menu:
          - ae01-unvotes.qmd
        
format:
  html:
    theme:
      - quartz
    css: styles.css
    toc: true

editor: visual

